# 2019-9-4

接 Promise 对象的内容

`Promise.prototype.finally()`，是在 Promise 对象状态改变后，不论最后状态如何，都会执行，就有点像 `try...catch...finally`

```JavaScript
promise
.then(result => {···})
.catch(error => {···})
.finally(() => {···});
```

`finally` 方法的回调函数没有任何参数，本质上是 then 方法的特例

```JavaScript
promise
.finally(() => {
  // 语句
});

// 等同于
promise
.then(
  result => {
    // 语句
    return result;
  },
  error => {
    // 语句
    throw error;
  }
);
```

但是很明显，要实现 `finally` 其实就是把相同的代码在 Promise 调用成功和失败的情况都写一次整合成了一次，所以来看看它的实现

```JavaScript
Promise.prototype.finally = function (callback) {
  let P = this.constructor;
  return this.then(
    value  => P.resolve(callback()).then(() => value),
    reason => P.resolve(callback()).then(() => { throw reason })
  );
};
```

但是只要知道一下就行了，不必深究，但是这么实现也有好处，`finally` 方法总是会返回原来的值

```JavaScript
// resolve 的值是 undefined
Promise.resolve(2).then(() => {}, () => {})
// resolve 的值是 2
Promise.resolve(2).finally(() => {})
// reject 的值是 undefined
Promise.reject(3).then(() => {}, () => {})
// reject 的值是 3
Promise.reject(3).finally(() => {})
```

`Promise.all()` 用来把很多个 Promise 实例，包装成一个新的 Promise 实例，接收一个 Promise 实例的数组作为参数，其实也不一定要是数组，具有 Iterator 接口，且返回的每个成员都是 Promise 的也可以

```JavaScript
const p = Promise.all([p1, p2, p3]);
```

如果数组成员不是 Promise 实例，则会先调用 `Promise.resolve` 方法，将参数转为 Promise 实例

生成的 Promise 实例的状态是由数组成员的状态决定的，只有数组成员的状态全变成 `fulfilled`，它的状态才会变成 `fulfilled`，此时，数组中 Promise 实例的返回值会被包装成数组，传递给它，只要数组成员的状态有一个变成 `rejected`，那它的状态就会变成 `rejected`，此时第一个被 `reject` 的实例的返回值会被传递给它，举个例子

```JavaScript
// 生成一个Promise对象的数组
const promises = [2, 3, 5, 7, 11, 13].map(function (id) {
  return getJSON('/post/' + id + ".json");
});

Promise.all(promises).then(function (posts) {
  // ...
}).catch(function(reason){
  // ...
});
```

`promises` 是包含 6 个 Promise 实例的数组，只有这 6 个实例的状态都变成 `fulfilled`，或者其中有一个变为 `rejected`，才会调用 `Promise.all` 方法后面的回调函数
来看看如何包装多个异步操作

```JavaScript
const databasePromise = connectDatabase();

const booksPromise = databasePromise
  .then(findAllBooks);

const userPromise = databasePromise
  .then(getCurrentUser);

Promise.all([
  booksPromise,
  userPromise
])
.then(([books, user]) => pickTopRecommendations(books, user));
```

`booksPromise` 和 `userPromise` 是两个异步操作，只有等到它们的结果都返回了，才会触发 `pickTopRecommendations` 这个回调函数

并且有个和 `async/await` 错误处理类似的，如果这个 Promise 实例，自己做了 `catch`，那他就算 `rejected` 也不会触发 `Promise.all()` 的 `catch` 方法

```JavaScript
const p1 = new Promise((resolve, reject) => {
  resolve('hello');
})
.then(result => result)
.catch(e => e);

const p2 = new Promise((resolve, reject) => {
  throw new Error('报错了');
})
.then(result => result)
.catch(e => e);

Promise.all([p1, p2])
.then(result => console.log(result))
.catch(e => console.log(e));
// ["hello", Error: 报错了]

const p1 = new Promise((resolve, reject) => {
  resolve('hello');
})
.then(result => result);

const p2 = new Promise((resolve, reject) => {
  throw new Error('报错了');
})
.then(result => result);

Promise.all([p1, p2])
.then(result => console.log(result))
.catch(e => console.log(e));
// Error: 报错了
```

`p1` 会 `resolved`，`p2` 会先 `rejected`，但是 `p2` 有 `catch` 方法，该方法返回的是一个新的 Promise 实例，所以 `p2` 指向的实际上是这个新的实例，该实例执行完 `catch` 方法后，也会变成 `resolved`，导致 `Promise.all` 方法参数里面的实例都 `resolved`，因此会调用 `then` 方法指定的回调函数，而不会调用 `catch` 方法指定的回调函数，如果把 `p2` 的 `catch` 去掉，那就会调用 `Promise.all()` 的 `catch` 方法

`Promise.race` 方法和 `Promise.all` 方法的参数以及功能类似，都是将多个 Promise 实例包装成一个新的 Promise 实例，若参数不是 Promise 实例，也会先调用 `Promise.resolve` 方法，但是 `Promise.race` 方法的状态是跟随率先改变状态的那个实例的

```JavaScript
const p = Promise.race([p1, p2, p3]);
```

只要 `p1`、`p2`、`p3` 之中有一个实例率先改变状态，`p` 的状态就跟着改变，那个率先改变的 Promise 实例的返回值，就传递给 `p` 的回调函数

一个例子，看起来有些像自定义的请求超时

```JavaScript
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
```

如果 5 秒之内 `fetch` 方法无法返回结果，变量 `p` 的状态就会变为 `rejected`，从而触发 `catch` 方法指定的回调函数

`Promise.resolve` 方法能将现有对象转为 Promise 对象

```JavaScript
// 将 jQuery 生成的deferred对象，转为一个新的 Promise 对象
const jsPromise = Promise.resolve($.ajax('/whatever.json'));
```

其效果等于

```JavaScript
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```

`Promise.resolve` 参数的四种情况

- Promise 实例：不做任何改变，直接返回这个实例

- `thenable` 对象：指的是具有 `then` 方法的对象，比如

```JavaScript
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};
```

`Promise.resolve` 方法会将这个对象转为 Promise 对象，然后就立即执行 `thenable` 对象的 `then` 方法

```JavaScript
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
```

`thenable` 对象的 `then` 方法执行后，对象 `p1` 的状态就变为 `resolved`，从而立即执行最后那个 `then` 方法指定的回调函数，输出 42

- 不具有 `then` 方法的对象，或不是对象：返回一个新的 Promise 对象，状态为 `resolved`

```JavaScript
const p = Promise.resolve('Hello');

p.then(function (s){
  console.log(s)
});
// Hello
```

- 不带参数：直接返回一个 `resolved` 状态的 Promise 对象

```JavaScript
const p = Promise.resolve();

p.then(function () {
  // ...
});
```

需要注意的是，立即 `resolve()` 的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时

```JavaScript
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```

`setTimeout(fn, 0)` 在下一轮“事件循环”开始时执行，`Promise.resolve()` 在本轮“事件循环”结束时执行，`console.log('one')` 则是立即执行，因此最先输出，看起来又像是面试会坑人的地方

`Promise.reject()` 方法也会返回一个新的 Promise 实例，但它的状态为 `rejected`

```JavaScript
const p = Promise.reject('出错了');
// 等同于
const p = new Promise((resolve, reject) => reject('出错了'))

p.then(null, function (s) {
  console.log(s)
});
// 出错了
```

生成一个 Promise 对象的实例 `p`，状态为 `rejected`，回调函数会立即执行

它的参数会直接作为 `reject` 的理由，不做加工处理

```JavaScript
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true
```

`Promise.reject` 方法的参数是一个 `thenable` 对象，执行以后，后面 `catch` 方法的参数不是 `reject` 抛出的“出错了”这个字符串，而是 `thenable` 对象

论 `Promise` 的应用，任何需要加载的地方，异步也好，加载资源也好，都能使用，也是最常用的地方，还能和 Generator 函数进行结合管理流程，遇到异步操作的时候，通常返回一个 Promise 对象

```JavaScript
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

const g = function* () {
  try {
    const foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  const it = generator();

  function go(result) {
    if (result.done) return result.value;

    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
```

Generator 函数 `g` 之中，有一个异步操作 `getFoo`，它返回的就是一个 Promise 对象，函数 `run` 用来处理这个 Promise 对象，并调用下一个 `next` 方法

`Promise.try` 还是一个提案，具体看[这里](http://es6.ruanyifeng.com/#docs/promise#Promise-try)
