# 2019-11-4

`async` 函数就是 Generator 函数的语法糖

```JavaScript
const fs = require('fs');

const readFile = function (fileName) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fileName, function(error, data) {
      if (error) return reject(error);
      resolve(data);
    });
  });
};

const gen = function* () {
  const f1 = yield readFile('/etc/fstab');
  const f2 = yield readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};

// 使用 async 函数改写
const asyncReadFile = async function () {
  const f1 = await readFile('/etc/fstab');
  const f2 = await readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};
```

`async` 函数对 Generator 函数的改进，体现在以下四点：内置执行器、更好的语义、更广的适用性、返回值是 Promise

`async` 函数返回一个 Promise 对象，可以使用 `then` 方法添加回调函数，当函数执行的时候，一旦遇到 `await` 就会先返回，等到异步操作完成，再接着执行函数体内后面的语句

```JavaScript
async function getStockPriceByName(name) {
  const symbol = await getStockSymbol(name);
  const stockPrice = await getStockPrice(symbol);
  return stockPrice;
}

getStockPriceByName('goog').then(function (result) {
  console.log(result);
});
```

`async` 函数有多种使用形式

```JavaScript
// 函数声明
async function foo() {}

// 函数表达式
const foo = async function () {};

// 对象的方法
let obj = { async foo() {} };
obj.foo().then(...)

// Class 的方法
class Storage {
  constructor() {
    this.cachePromise = caches.open('avatars');
  }

  async getAvatar(name) {
    const cache = await this.cachePromise;
    return cache.match(`/avatars/${name}.jpg`);
  }
}

const storage = new Storage();
storage.getAvatar('jake').then(…);

// 箭头函数
const foo = async () => {};
```

`async` 函数的语法规则总体上比较简单，难点是错误处理机制

`async` 函数返回一个 Promise 对象，`async` 函数内部 `return` 语句返回的值，会成为 `then` 方法回调函数的参数

```JavaScript
async function f() {
  return 'hello world';
}

f().then(v => console.log(v))
// "hello world"
```

`async` 函数内部抛出错误，会导致返回的 Promise 对象变为 `reject` 状态，抛出的错误对象会被 `catch` 方法回调函数接收到

`async` 函数返回的 Promise 对象，必须等到内部所有 `await` 命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到 `return` 语句或者抛出错误

正常情况下，`await` 命令后面是一个 Promise 对象，返回该对象的结果，如果不是 Promise 对象，就直接返回对应的值，另一种情况是，`await` 命令后面是一个 `thenable` 对象（即定义 `then` 方法的对象），那么 `await` 会将其等同于 Promise 对象，`await` 可以让程序停顿指定的时间，`await` 命令后面的 Promise 对象如果变为 `reject` 状态，则 `reject` 的参数会被 `catch` 方法的回调函数接收到，任何一个 `await` 语句后面的 Promise 对象变为 `reject` 状态，那么整个 `async` 函数都会中断执行

有时，我们希望即使前一个异步操作失败，也不要中断后面的异步操作，这时可以将第一个 `await` 放在 `try...catch` 结构里面，这样不管这个异步操作是否成功，第二个 `await` 都会执行

```JavaScript
async function f() {
  try {
    await Promise.reject('出错了');
  } catch(e) {
  }
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))
// hello world
```

另一种方法是 `await` 后面的 Promise 对象再跟一个 `catch` 方法，处理前面可能出现的错误

```JavaScript
async function f() {
  await Promise.reject('出错了')
    .catch(e => console.log(e));
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))
// 出错了
// hello world
```
